#!/usr/bin/env node
/**
 * 把 src/assets/*.svg 生成成 C 头文件 src/generated/icon_svgs.h，
 * 以及（macOS 有 clang 时）Swift 图标文件 src/generated/icon_svgs.swift。
 *
 * C 输出形如：
 *   static const char* kIconSvg_Rect = "<svg ...>...</svg>";
 * SVG 原文原样保留（含 currentColor），运行时再把 currentColor 替换成
 * 目标颜色（normal/hover/active 三态），从而一套文本支持多色。
 *
 * Swift 输出：生成期用 clang 现编一个极小 nanosvg 光栅化辅助程序
 * （单实例化编译单元，参照 icons_windows.cpp 的宏实例化写法），把每个 SVG
 * （currentColor→黑色）光栅化为 PNG（2x、内容 72% 居中）→ base64 内联进
 * icon_svgs.swift；运行时 NSImage(data:) 解码为 template 图标并按需着色出
 * normal/hover/active 三态缓存，等价 Windows icons_windows.cpp 的双色位图缓存。
 * clang 不可用（如 Windows）时跳过 Swift 输出（文件已提交进仓库，不受影响）。
 *
 * 自动生成，请勿手动编辑。重新生成命令：node scripts/gen-icons.js
 */
const fs = require('fs');
const os = require('os');
const path = require('path');
const zlib = require('zlib');
const { execFileSync } = require('child_process');

// 工具栏按钮 -> SVG 文件名映射（顺序与 src/screenshot/windows/internal.h 的 ToolButton 枚举一致）
// 分隔线（Separator）对应 null，不生成图标。
const ICON_MAP = {
  Drag: 'drag',
  Rect: 'square',
  Circle: 'circle',
  Arrow: 'arrow-up-right',
  Brush: 'pencil',
  Mosaic: 'mosaic',
  Text: 'text',
  Translate: 'translate',
  LongCapture: 'long-capture',
  Undo: 'arrow-back-up',
  Redo: 'arrow-forward-up',
  Save: 'download',
  Cancel: 'x',
  Confirm: 'check',
  // —— 长截图工具栏专用图标（不进 kIconSvgs 数组，长截图窗口按名直取常量）——
  DirectionV: 'direction-vertical',
  DirectionH: 'direction-horizontal',
  AutoScrollV: 'auto-scroll-vertical',
  AutoScrollH: 'auto-scroll-horizontal',
  CropIcon: 'crop',
  // —— 长截图裁剪 popover 子操作图标 ——
  CropDiscardTop: 'crop-discard-top',
  CropDiscardBottom: 'crop-discard-bottom',
  CropDiscardLeft: 'crop-discard-left',
  CropDiscardRight: 'crop-discard-right',
  CropReset: 'crop-reset',
};

const ASSETS_DIR = path.join(__dirname, '..', 'src', 'assets');
const OUT_DIR = path.join(__dirname, '..', 'src', 'generated');
const OUT_FILE = path.join(OUT_DIR, 'icon_svgs.h');
const OUT_SWIFT_FILE = path.join(OUT_DIR, 'icon_svgs.swift');

// Swift 图标 PNG 光栅化边长（物理像素）：逻辑 26pt（= Windows CalcToolbarMetrics.iconSize
// = SC_TOOLBAR_BTN-8+2）× 2（Retina 2x，绘制到 26pt 矩形时逐像素对齐）。
const SWIFT_ICON_PX = 52;

// ---------------- PNG 编码（Node 内置 zlib，无第三方依赖） ----------------

// CRC32 查表（PNG chunk 校验用）
const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
    t[n] = c >>> 0;
  }
  return t;
})();

function crc32(buf) {
  let c = 0xFFFFFFFF;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xFF] ^ (c >>> 8);
  return (c ^ 0xFFFFFFFF) >>> 0;
}

function pngChunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length, 0);
  const typeBuf = Buffer.from(type, 'ascii');
  const crcBuf = Buffer.alloc(4);
  crcBuf.writeUInt32BE(crc32(Buffer.concat([typeBuf, data])), 0);
  return Buffer.concat([len, typeBuf, data, crcBuf]);
}

/** RGBA 原始字节 → PNG（8bit RGBA、filter 0；仅生成期使用）。 */
function encodePng(width, height, rgba) {
  const stride = width * 4;
  const raw = Buffer.alloc((stride + 1) * height);
  for (let y = 0; y < height; y++) {
    raw[y * (stride + 1)] = 0; // filter type 0（None）
    rgba.copy(raw, y * (stride + 1) + 1, y * stride, (y + 1) * stride);
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8;  // bit depth
  ihdr[9] = 6;  // color type RGBA
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]),
    pngChunk('IHDR', ihdr),
    pngChunk('IDAT', zlib.deflateSync(raw, { level: 9 })),
    pngChunk('IEND', Buffer.alloc(0)),
  ]);
}

// ---------------- 生成期 nanosvg 光栅化辅助程序（clang 现编现用） ----------------

// 极小 C 程序：把每个 SVG（currentColor→黑）光栅化为 px×px RGBA 原始文件。
// NANOSVG_IMPLEMENTATION / NANOSVGRAST_IMPLEMENTATION 在同一编译单元各展开一次
//（与 Windows icons_windows.cpp 的单实例化写法一致）。
const RASTERIZER_C_TEMPLATE = `/* AUTO-GENERATED by scripts/gen-icons.js — 生成期临时文件，用完即删 */
#define NANOSVG_IMPLEMENTATION
#include "nanosvg.h"
#define NANOSVGRAST_IMPLEMENTATION
#include "nanosvgrast.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { const char* key; const char* svg; } IconEntry;

static const IconEntry kIcons[] = {
__ICON_ENTRIES__
};

/* 把 src 中所有 token 替换为 rep 后写入 dst（rep 比 token 短，dst 容量取 src 长度 + 1 即可） */
static void replaceToken(char* dst, const char* src, const char* token, const char* rep) {
    const size_t tlen = strlen(token);
    const size_t rlen = strlen(rep);
    const char* p = src;
    char* w = dst;
    const char* hit;
    while ((hit = strstr(p, token)) != NULL) {
        memcpy(w, p, (size_t)(hit - p));
        w += hit - p;
        memcpy(w, rep, rlen);
        w += rlen;
        p = hit + tlen;
    }
    strcpy(w, p);
}

int main(int argc, char** argv) {
    if (argc < 3) { fprintf(stderr, "usage: rasterizer <outDir> <px>\\n"); return 1; }
    const char* outDir = argv[1];
    const int px = atoi(argv[2]);
    NSVGrasterizer* rast = nsvgCreateRasterizer();
    if (!rast) return 1;
    for (int i = 0; i < (int)(sizeof(kIcons) / sizeof(kIcons[0])); i++) {
        /* currentColor -> 黑色（nsvgParse 会就地改写 buffer，需可写副本） */
        char* buf = (char*)malloc(strlen(kIcons[i].svg) + 1);
        if (!buf) continue;
        replaceToken(buf, kIcons[i].svg, "currentColor", "#000000");
        NSVGimage* image = nsvgParse(buf, "px", 96.0f);
        if (!image) { free(buf); continue; }
        unsigned char* rgba = (unsigned char*)calloc((size_t)px * px * 4, 1);
        if (rgba) {
            /* 内容缩放到 72% 并居中（与 Windows icons_windows.cpp RenderSvgToBitmap 一致） */
            const float contentScale = 0.72f;
            const float pad = (1.0f - contentScale) * 0.5f;
            float refSize = (image->width > 0) ? image->width
                          : (image->height > 0) ? image->height : 24.0f;
            float scale = (float)px * contentScale / refSize;
            nsvgRasterize(rast, image, px * pad, px * pad, scale, rgba, px, px, px * 4);
            char outPath[1024];
            snprintf(outPath, sizeof(outPath), "%s/%s.rgba", outDir, kIcons[i].key);
            FILE* f = fopen(outPath, "wb");
            if (f) {
                fwrite(rgba, 1, (size_t)px * px * 4, f);
                fclose(f);
            }
            free(rgba);
        }
        nsvgDelete(image);
        free(buf);
    }
    nsvgDeleteRasterizer(rast);
    return 0;
}
`;

/** 生成期光栅化：返回 { key -> base64 PNG }；clang/编译失败返回 null（调用方跳过 Swift 输出）。 */
function rasterizeIconsToPngBase64(assetsByKey) {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ztools-icons-'));
  try {
    const cPath = path.join(tmpDir, 'rasterizer.c');
    const binPath = path.join(tmpDir, 'rasterizer');
    const entries = Object.entries(assetsByKey)
      .map(([key, svg]) => `    {"${key}",\n     "${svg.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"},`)
      .join('\n');
    fs.writeFileSync(cPath, RASTERIZER_C_TEMPLATE.replace('__ICON_ENTRIES__', entries), 'utf8');
    execFileSync('clang', ['-O2', '-std=c99', '-o', binPath, cPath,
      '-I', path.join(__dirname, '..', 'src', 'third_party')], { stdio: 'inherit' });
    const outDir = path.join(tmpDir, 'out');
    fs.mkdirSync(outDir, { recursive: true });
    execFileSync(binPath, [outDir, String(SWIFT_ICON_PX)], { stdio: 'inherit' });

    const result = {};
    for (const key of Object.keys(assetsByKey)) {
      const rawPath = path.join(outDir, `${key}.rgba`);
      const rgba = fs.readFileSync(rawPath);
      if (rgba.length !== SWIFT_ICON_PX * SWIFT_ICON_PX * 4) {
        throw new Error(`unexpected rgba size for ${key}: ${rgba.length}`);
      }
      result[key] = encodePng(SWIFT_ICON_PX, SWIFT_ICON_PX, rgba).toString('base64');
    }
    return result;
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
}

// ---------------- Swift 输出 ----------------

/** ICON_MAP 键 → Swift 枚举 case 名（首字母小写驼峰化）。 */
function swiftCaseName(key) {
  const name = key.charAt(0).toLowerCase() + key.slice(1);
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) {
    throw new Error(`ICON_MAP key ${key} is not a valid Swift identifier`);
  }
  return name;
}

/** 生成 src/generated/icon_svgs.swift（base64 PNG 表 + template 着色运行时）。 */
function writeSwiftOutput(pngBase64ByKey) {
  const keys = Object.keys(ICON_MAP);
  // 防漂移断言：ICON_MAP 键 ↔ Swift 枚举 case 必须一一对齐（数量与顺序同源生成，
  // 此处再显式校验一次，ICON_MAP 结构变化时立即报错而非静默漂移）。
  const cases = keys.map(swiftCaseName);
  if (new Set(cases).size !== cases.length) {
    throw new Error('ICON_MAP keys collide after camelCase conversion');
  }
  const lines = [];
  lines.push('import AppKit');
  lines.push('');
  lines.push('// AUTO-GENERATED by scripts/gen-icons.js — DO NOT EDIT.');
  lines.push('// 生成方式：node scripts/gen-icons.js（构建期工具；src/assets/*.svg 经 clang 现编的');
  lines.push('// nanosvg 极小光栅化辅助程序渲染为 PNG（currentColor→黑、2x、内容 72% 居中）→ base64。');
  lines.push('// 运行时 NSImage(data:) 解码为 template 图标，按需着色出 normal/hover/active 三态缓存，');
  lines.push('// 等价 Windows icons_windows.cpp SCIconCache 的 dark/active 双色位图缓存语义。');
  lines.push('// 重新生成命令：node scripts/gen-icons.js');
  lines.push('');
  lines.push('/// 工具栏图标枚举：raw 值按 scripts/gen-icons.js ICON_MAP 顺序对齐（键名首字母小写化），');
  lines.push('/// 生成器内已断言 ICON_MAP 键与本枚举一一对齐（防漂移）。分隔线无图标不列入。');
  lines.push('enum SCToolbarIcon: Int, CaseIterable {');
  cases.forEach((name, i) => {
    lines.push(`    case ${name} = ${i}`);
  });
  lines.push('}');
  lines.push('');
  lines.push('/// base64 PNG 表（顺序与 SCToolbarIcon.allCases 一致，由生成器保证）。');
  lines.push('private let kIconPngBase64: [String] = [');
  keys.forEach((key) => {
    lines.push(`    /* ${swiftCaseName(key)} */ "${pngBase64ByKey[key]}",`);
  });
  lines.push(']');
  lines.push('');
  lines.push('extension SCToolbarIcon {');
  lines.push('    /// 图标绘制逻辑边长（对齐 Windows CalcToolbarMetrics.iconSize = SC_TOOLBAR_BTN-8+2；');
  lines.push('    /// 生成 PNG 为其 2x 物理像素，Retina 下逐像素清晰）。');
  lines.push('    static let iconPointSize: CGFloat = 26');
  lines.push('');
  lines.push('    private static let cacheLock = NSLock()');
  lines.push('    private static var baseCache: [Int: NSImage] = [:]');
  lines.push('    private static var tintedCache: [String: NSImage] = [:]');
  lines.push('');
  lines.push('    /// 解码原始 PNG 为 template 图标（isTemplate=true，颜色语义仅保留 alpha）。');
  lines.push('    /// 解码结果按 rawValue 缓存，重复取用零开销（等价 Windows 位图缓存的命中路径）。');
  lines.push('    var baseImage: NSImage? {');
  lines.push('        if let hit = SCToolbarIcon.baseCache[rawValue] { return hit }');
  lines.push('        guard rawValue >= 0, rawValue < kIconPngBase64.count,');
  lines.push('              let data = Data(base64Encoded: kIconPngBase64[rawValue]),');
  lines.push('              let image = NSImage(data: data) else { return nil }');
  lines.push('        image.isTemplate = true');
  lines.push('        image.size = NSSize(width: SCToolbarIcon.iconPointSize, height: SCToolbarIcon.iconPointSize)');
  lines.push('        SCToolbarIcon.baseCache[rawValue] = image');
  lines.push('        return image');
  lines.push('    }');
  lines.push('');
  lines.push('    /// 按指定颜色着色的图标副本：纯色填充后以 destinationIn 用底图 alpha 裁形，');
  lines.push('    /// 得到任意单色版本（normal 深灰 / active 主题蓝 / 置灰半透明）。');
  lines.push('    /// 结果按「图标+颜色」缓存，三态派生只算一次（等价 Windows dark/active 双色缓存）。');
  lines.push('    /// - Parameter color: 目标着色（sRGB）');
  lines.push('    /// - Returns: 着色后的 26pt 图标；解码失败返回 nil');
  lines.push('    func tinted(_ color: NSColor) -> NSImage? {');
  lines.push('        guard let srgb = color.usingColorSpace(.sRGB) else { return baseImage }');
  lines.push('        let key = String(format: "%d-%02X%02X%02X%02X", rawValue,');
  lines.push('                         Int(srgb.redComponent * 255), Int(srgb.greenComponent * 255),');
  lines.push('                         Int(srgb.blueComponent * 255), Int(srgb.alphaComponent * 255))');
  lines.push('        if let hit = SCToolbarIcon.tintedCache[key] { return hit }');
  lines.push('        guard let base = baseImage else { return nil }');
  lines.push('        let image = NSImage(size: base.size, flipped: false) { rect in');
  lines.push('            srgb.setFill()');
  lines.push('            rect.fill()');
  lines.push('            base.draw(in: rect, from: .zero, operation: .destinationIn, fraction: 1.0)');
  lines.push('            return true');
  lines.push('        }');
  lines.push('        image.isTemplate = false');
  lines.push('        SCToolbarIcon.tintedCache[key] = image');
  lines.push('        return image');
  lines.push('    }');
  lines.push('}');
  lines.push('');
  fs.writeFileSync(OUT_SWIFT_FILE, lines.join('\n'), 'utf8');
}

// ---------------- C 头文件输出 ----------------

function writeHeaderOutput() {
  const lines = [];
  lines.push('#pragma once');
  lines.push('// AUTO-GENERATED by scripts/gen-icons.js — DO NOT EDIT.');
  lines.push('// SVG 原文保留 currentColor，运行时替换为目标颜色。');
  lines.push('');
  for (const [key, fileBase] of Object.entries(ICON_MAP)) {
    const svgPath = path.join(ASSETS_DIR, `${fileBase}.svg`);
    if (!fs.existsSync(svgPath)) {
      console.error(`✖ missing svg: ${svgPath}`);
      process.exit(1);
    }
    const raw = fs.readFileSync(svgPath, 'utf8').trim();
    // 折叠成单行，去掉换行，再按 C 字面量拼接（更紧凑）
    const oneLine = raw.replace(/\r?\n/g, '').replace(/\s+/g, ' ');
    lines.push(`static const char* kIconSvg_${key} =`);
    lines.push(`    "${oneLine.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}";`);
    lines.push('');
  }

  // 所有图标文本的数组（按 ToolButton 枚举顺序，分隔线为 nullptr）
  lines.push('// 按 ToolButton 枚举顺序的 SVG 文本数组，分隔线为 nullptr。');
  lines.push('static const char* const kIconSvgs[] = {');
  // 顺序：Drag Rect Circle Arrow Brush Mosaic Text Translate LongCapture SEP1 Undo Redo SEP2 Save Cancel Confirm
  lines.push('    kIconSvg_Drag, kIconSvg_Rect, kIconSvg_Circle, kIconSvg_Arrow,');
  lines.push('    kIconSvg_Brush, kIconSvg_Mosaic, kIconSvg_Text, kIconSvg_Translate, kIconSvg_LongCapture, nullptr,');
  lines.push('    kIconSvg_Undo, kIconSvg_Redo, nullptr,');
  lines.push('    kIconSvg_Save, kIconSvg_Cancel, kIconSvg_Confirm');
  lines.push('};');
  lines.push('');

  fs.writeFileSync(OUT_FILE, lines.join('\n'), 'utf8');
}

function main() {
  if (!fs.existsSync(ASSETS_DIR)) {
    console.error(`✖ assets dir not found: ${ASSETS_DIR}`);
    process.exit(1);
  }
  fs.mkdirSync(OUT_DIR, { recursive: true });

  // 1) C 头文件（Windows 侧运行时光栅化的输入，全平台生成）
  writeHeaderOutput();
  console.log(`✓ generated ${path.relative(path.join(__dirname, '..'), OUT_FILE)} (${Object.keys(ICON_MAP).length} icons)`);

  // 2) Swift 输出（生成期光栅化；无 clang 的环境跳过——文件已提交进仓库）
  let hasClang = false;
  if (process.platform === 'darwin') {
    try {
      execFileSync('clang', ['--version'], { stdio: 'ignore' });
      hasClang = true;
    } catch {
      hasClang = false;
    }
  }
  if (!hasClang) {
    console.log('ℹ clang unavailable - skip icon_svgs.swift regeneration (committed file kept)');
    return;
  }

  const assetsByKey = {};
  for (const [key, fileBase] of Object.entries(ICON_MAP)) {
    const svgPath = path.join(ASSETS_DIR, `${fileBase}.svg`);
    if (!fs.existsSync(svgPath)) {
      console.error(`✖ missing svg: ${svgPath}`);
      process.exit(1);
    }
    assetsByKey[key] = fs.readFileSync(svgPath, 'utf8').trim().replace(/\r?\n/g, '').replace(/\s+/g, ' ');
  }
  const pngBase64ByKey = rasterizeIconsToPngBase64(assetsByKey);
  writeSwiftOutput(pngBase64ByKey);
  console.log(`✓ generated ${path.relative(path.join(__dirname, '..'), OUT_SWIFT_FILE)} (${Object.keys(ICON_MAP).length} icons, ${SWIFT_ICON_PX}px PNG @2x)`);
}

main();
