#!/usr/bin/env node
/**
 * 把 src/assets/*.svg 生成成 C 头文件 src/generated/icon_svgs.h。
 *
 * 输出形如：
 *   static const char* kIconSvg_Rect = "<svg ...>...</svg>";
 *
 * SVG 原文原样保留（含 currentColor），运行时再把 currentColor 替换成
 * 目标颜色（normal/hover/active 三态），从而一套文本支持多色。
 *
 * 自动生成，请勿手动编辑。
 */
const fs = require('fs');
const path = require('path');

// 工具栏按钮 -> SVG 文件名映射（顺序与 src/screenshot_windows.cpp 的 ToolButton 枚举一致）
// 分隔线（Separator）对应 null，不生成图标。
const ICON_MAP = {
  Drag: 'drag',
  Rect: 'square',
  Circle: 'circle',
  Arrow: 'arrow-up-right',
  Brush: 'pencil',
  Mosaic: 'mosaic',
  Text: 'text',
  Translate: 'translate',
  Undo: 'arrow-back-up',
  Redo: 'arrow-forward-up',
  Save: 'download',
  Cancel: 'x',
  Confirm: 'check',
};

const ASSETS_DIR = path.join(__dirname, '..', 'src', 'assets');
const OUT_DIR = path.join(__dirname, '..', 'src', 'generated');
const OUT_FILE = path.join(OUT_DIR, 'icon_svgs.h');

// C 字符串字面量转义：处理 " \ 和换行
function toCLiteral(str) {
  // 把字符串按行拆开，每行用独立字面量拼接，保证可读性且避免超长行
  return str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .split(/\r?\n/)
    .map((line) => `    "${line}"`)
    .join('\n');
}

function main() {
  if (!fs.existsSync(ASSETS_DIR)) {
    console.error(`✖ assets dir not found: ${ASSETS_DIR}`);
    process.exit(1);
  }
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const lines = [];
  lines.push('#pragma once');
  lines.push('// AUTO-GENERATED by scripts/gen-icons.js — DO NOT EDIT.');
  lines.push('// SVG 原文保留 currentColor，运行时替换为目标颜色。');
  lines.push('');

  for (const [key, fileBase] of Object.entries(ICON_MAP)) {
    const svgPath = path.join(ASSETS_DIR, `${fileBase}.svg`);
    if (!fs.existsSync(svgPath)) {
      console.error(`✖ missing svg: ${svgPath}`);
      process.exit(1);
    }
    const raw = fs.readFileSync(svgPath, 'utf8').trim();
    // 折叠成单行，去掉换行，再按 C 字面量拼接（更紧凑）
    const oneLine = raw.replace(/\r?\n/g, '').replace(/\s+/g, ' ');
    lines.push(`static const char* kIconSvg_${key} =`);
    lines.push(`    "${oneLine.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}";`);
    lines.push('');
  }

  // 所有图标文本的数组（按 ToolButton 枚举顺序，分隔线为 nullptr）
  lines.push('// 按 ToolButton 枚举顺序的 SVG 文本数组，分隔线为 nullptr。');
  lines.push('static const char* const kIconSvgs[] = {');
  // 顺序：Drag Rect Circle Arrow Brush Mosaic Text Translate SEP1 Undo Redo SEP2 Save Cancel Confirm
  lines.push('    kIconSvg_Drag, kIconSvg_Rect, kIconSvg_Circle, kIconSvg_Arrow,');
  lines.push('    kIconSvg_Brush, kIconSvg_Mosaic, kIconSvg_Text, kIconSvg_Translate, nullptr,');
  lines.push('    kIconSvg_Undo, kIconSvg_Redo, nullptr,');
  lines.push('    kIconSvg_Save, kIconSvg_Cancel, kIconSvg_Confirm');
  lines.push('};');
  lines.push('');

  fs.writeFileSync(OUT_FILE, lines.join('\n'), 'utf8');
  console.log(`✓ generated ${path.relative(path.join(__dirname, '..'), OUT_FILE)} (${Object.keys(ICON_MAP).length} icons)`);
}

main();
